# Generated by Django 4.2.6 on 2023-10-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_delete_blog_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='Признак публикации'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.CharField(max_length=150, verbose_name='slug'),
        ),
    ]
