# Generated by Django 4.2.6 on 2023-10-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_blog_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_record',
        ),
    ]
