# Generated by Django 4.2.6 on 2023-10-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('is_active',), 'verbose_name': 'версия', 'verbose_name_plural': 'версии'},
        ),
    ]
